### ISSUE TITLE
incompatibility with Oracle Linux 8 arm

### ISSUE THREAD

**Issue by amosbin** [nicmcd/vcgencmd#2]
I have the following outputs:
```
$ python3 --version
Python 3.8.0

$ python3 -m pip --version
pip 20.1.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

$ python3 -m pip install setuptools
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (41.6.0)

$ python3 -m pip install vcgencmd
Requirement already satisfied: vcgencmd in /usr/local/lib/python3.8/site-packages (0.1.1)
```
from what I understand, I have everything i need for vcgencmd to work. python and its package manager pip, then the setuptools dependency all installed.
then finally vcgencmd also installed.
yet when I run:
`$ python3 -m vcgencmd`
I get:
```
File "/usr/local/lib/python3.8/site-packages/vcgencmd/__init__.py", line 4, in <module>
    subprocess.check_output("vcgencmd")
  File "/usr/lib64/python3.8/subprocess.py", line 411, in check_output   
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,     
  File "/usr/lib64/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__       
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vcgencmd'       

During handling of the above exception, another exception occurred:      

Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 183, in _run_module_as_main 
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.8/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.8/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/site-packages/vcgencmd/__init__.py", line 6, in <module>
    raise ImportError("\"vcgencmd\" command not found")
ImportError: "vcgencmd" command not found
```
am I doing something wrong or this is actually a bug

**Comment by nicmcd** [comment]
What is `steptools`? I think you are looking for `setuptools`!

**Comment by amosbin** [comment]
> What is `steptools`? I think you are looking for `setuptools`!

sorry, it was a typo.
i rewrote the issue. with the output I got.
thank you for your reply.

**Comment by nicmcd** [comment]
This python library is just a wrapper around the Rasberry PI command "vcgencmd". Documentation is here: https://www.raspberrypi.org/documentation/raspbian/applications/vcgencmd.md

The python wrapper library most certainly will not work if "vcgencmd" is not installed on your system.

**Comment by nicmcd** [comment]
Are you able to run vcgencmd from the command line?
