### ISSUE TITLE
Program doesn't work after installation - Issue with imports and package paths

### ISSUE THREAD

**Issue by adamency** [nicmcd/vcgencmd#6]
Hi @nicmcd 

I know this project is 10 years old, but your interactions in latest issues seems to indicate you believe it should still work (at least in 2020).

### System

- The machine is a rpi 4.
- Debian 12 OS (so not native raspberry OS)
- Everything is run as `root` user

### Installation

Here is the installation command I used (with `python3-pip` and `python3-setuptools` already installed) :

```
pip3 install git+https://github.com/nicmcd/vcgencmd.git --break-system-packages
```

with the option used because current default python3-pip install is set to externally managed python packages via apt instead (like most major distros nowadays).

The package is then installed to `usr/local/lib/python3.11/dist-packages/vcgencmd`

#### 1st Attempt

When trying to run the command with `python3 -m vcgencmd` (because there is no direct `vcgencmd` installed), python crashes with this traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/vcgencmd/__init__.py", line 20, in <module>
    subprocess.check_output('vcgencmd')
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vcgencmd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
/usr/bin/python3: No module named vcgencmd
```

#### 2nd Attempt

And as I believed it was a path/CWD issue, I tried going to the aforementioned package directory and run:

```
python3 vcgencmd.py
```

which exited with no output at all.

**Comment by adamency** [comment]
This package is indeed simply a binding to the actual executable of the same name. This homonymy threw me off. @nicmcd I understand you already stated this in the readme, but I believe it would have been more appropriate to find a different name like `python-vcgencmd` or similar. Anyway, the readme of https://github.com/raspberrypi/userland seems to indicate all this is deprecated anyway today. Closing.
